apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
#encrypted username  base 64-> mongouser-> bw9uZ291...
  mongo-user: bW9uZ291c2Vy
  #encrypted password-> mongopassword-> bW9uZ29w...
  mongo-password: bW9uZ29wYXNzd29yZA==